plugins {
    id 'com.android.application'
}

android {
    namespace 'com.roman.tvportal'
    compileSdk 34

    defaultConfig {
        applicationId 'com.roman.tvportal'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            // Подписываем debug-ключом, чтобы release-APK тоже можно было сразу установить
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
